openapi: 3.0.0

info:
  version: v1
  title: crawler

servers:
  - url: 'http://localhost:8080'

paths:
  /api/fetcher:
    get:
      description: Returns a list of crawler tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      description: Creates a new crawler task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Successful response
        '400':
          description: Invalid task specification


  /api/fetcher/{id}:
    delete:
      description: Removes the specified task (it will no longer be fetched)
      parameters:
        - in: path
          name: id
          description: "id of the task that should be deleted"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
        '404':
          description: A task with the specified id didn't exist


  /api/fetcher/{id}/history:
    get:
      description: Returns a list of responses for a given task
      parameters:
        - in: path
          name: id
          description: "id of the task for which te history of responses should be displayed"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attempt'
        '404':
          description: A task with the specified id didn't exist


components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: number
        url:
          type: string
          example: "http://responder:8080/range/1000"
        interval:
          type: number
          example: 1
          description: how often the url should be fetched (in seconds)
    Attempt:
      type: object
      properties:
        response:
          type: string
        created_at:
          type: number
        duration:
          type: number
          description: a time time it took to fetch the url